export const LOCATIONS = [
  {
    key: "wynne",
    name: "Wynne",
    address: "585 Falls Blvd S, Wynne, AR 72396",
    phone: "(870) 238-3300",
    hours: "Mon to Fri, 8:00 a.m. to 5:00 p.m.",
    services: ["Primary care", "Urgent care", "Wound care", "Pediatrics", "Women health"],
    coords: { lat: 35.2240, lng: -90.7867 },
    region: "Cross County",
    waitBase: 12,
    waitJitter: 8,
  },
  {
    key: "osceola",
    name: "Osceola",
    address: "Osceola, AR 72370",
    phone: "(870) 563-7700",
    hours: "Mon to Fri, 8:00 a.m. to 5:00 p.m.",
    services: ["Family medicine", "Urgent care", "Women health"],
    coords: { lat: 35.7045, lng: -89.9692 },
    region: "Mississippi County",
    waitBase: 8,
    waitJitter: 6,
  },
  {
    key: "lonoke",
    name: "Lonoke",
    address: "Lonoke, AR 72086",
    phone: "(501) 676-3000",
    hours: "Mon to Fri, 8:00 a.m. to 5:00 p.m.",
    services: ["Primary care", "Pediatrics", "Prevention"],
    coords: { lat: 34.7845, lng: -91.8985 },
    region: "Lonoke County",
    waitBase: 15,
    waitJitter: 10,
  },
  {
    key: "scott",
    name: "Scott",
    address: "Scott, AR 72142",
    phone: "(501) 961-1100",
    hours: "Mon to Fri, 8:00 a.m. to 5:00 p.m.",
    services: ["Primary care", "Med-Peds", "Chronic care"],
    coords: { lat: 34.7012, lng: -92.0937 },
    region: "Pulaski County",
    waitBase: 10,
    waitJitter: 7,
  },
];

export const SERVICES = [
  {
    key: "primary",
    name: "Primary Care",
    desc: "Whole-family preventive care, chronic condition management, annual wellness, and same-week access.",
    cta: "Book primary care",
    icon: "stethoscope",
    accent: "#1f3a2e",
  },
  {
    key: "pediatrics",
    name: "Pediatrics",
    desc: "Board-certified care for newborns to teens, with well visits, immunizations, and calm-first appointments.",
    cta: "Book pediatric visit",
    icon: "child",
    accent: "#c97b5a",
  },
  {
    key: "urgent",
    name: "Urgent Care",
    desc: "Stitches, illness, minor injuries, x-rays, and lab tests when you cannot wait days for an appointment.",
    cta: "Reserve urgent slot",
    icon: "bolt",
    accent: "#b8924a",
  },
  {
    key: "wound",
    name: "Wound Care",
    desc: "Advanced wound management led by certified specialists with healing protocols beyond standard dressing changes.",
    cta: "Start wound consult",
    icon: "leaf",
    accent: "#7a9885",
  },
  {
    key: "womens",
    name: "Women Health",
    desc: "Annual exams, screenings, contraception support, and trusted ongoing care delivered by women-focused providers.",
    cta: "Book women health visit",
    icon: "heart",
    accent: "#a85f3f",
  },
  {
    key: "occupational",
    name: "Occupational Health",
    desc: "Workplace injury care, return-to-work planning, drug screens, and employer health support across East Arkansas.",
    cta: "Request occupational care",
    icon: "shield",
    accent: "#2d4a3c",
  },
];

export const PROVIDERS = [
  {
    name: "Dr. Aaron Mitchell, MD",
    role: "Chief Medical Officer, Cofounder",
    specialty: "Family Medicine, Board Certified",
    tags: ["wynne", "primary"],
    accepting: true,
    featured: true,
    img: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=800&q=80&auto=format&fit=crop",
    bio: "Methodist Hospital Physician Leadership Academy delegate, recognized among the top 20 physicians in greater Memphis. Led the team to Level 3 PCMH Certification and Hypertension Champion recognition.",
    education: ["UAMS, Doctor of Medicine", "UAMS Family Medicine Residency, Jonesboro AR", "MBA, University of Arkansas at Little Rock"],
  },
  {
    name: "Stephen Andy Rohrer",
    role: "Chief Executive Officer, Cofounder",
    specialty: "MSN-RN, APRN, AGACNP-BC, FNP-BC, RNFA, CWS",
    tags: ["wynne", "primary", "wound"],
    accepting: true,
    featured: true,
    img: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=800&q=80&auto=format&fit=crop",
    bio: "Fifteen plus years in healthcare. Trained at UAB and UCA. Board certified in hospital medicine, family medicine, and advanced wound management. Dedicated to better access for the Delta.",
    education: ["MSN, University of Alabama Birmingham", "BSN, University of Central Arkansas"],
  },
  {
    name: "Dr. Hong-Van Nguyen, MD",
    role: "Pediatrics",
    specialty: "Pediatric Care",
    tags: ["wynne", "pediatrics", "spanish"],
    accepting: true,
    languages: ["English", "Vietnamese", "Spanish"],
    img: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=800&q=80&auto=format&fit=crop",
    bio: "From New Orleans. Medical degree from LSU New Orleans, pediatric residency at UAMS Little Rock with training at Arkansas Children Hospital. Believes in calm child-friendly visits.",
    education: ["LSU New Orleans, Doctor of Medicine", "UAMS Pediatric Residency"],
  },
  {
    name: "Erica Dewey, MD",
    role: "Family Medicine",
    specialty: "Women Health, Pediatrics, Preventative Care",
    tags: ["lonoke", "primary", "womens", "pediatrics", "spanish"],
    accepting: true,
    languages: ["English", "Spanish"],
    img: "https://images.unsplash.com/photo-1607990281513-2c110a25bd8c?w=800&q=80&auto=format&fit=crop",
    bio: "Born and raised in Arkansas. UAMS medical school. Chief resident at Baptist Health-UAMS in North Little Rock. Passionate about women health, pediatrics, and chronic disease management.",
    education: ["UAMS, Doctor of Medicine", "Baptist Health-UAMS Residency, Chief Resident"],
  },
  {
    name: "Zoe Weeks, MD",
    role: "Internal Medicine and Pediatrics",
    specialty: "Combined Med-Peds",
    tags: ["scott", "primary", "pediatrics"],
    accepting: true,
    img: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=800&q=80&auto=format&fit=crop",
    bio: "Northeast Arkansas native. Taught 7th grade math through Teach For America before medical school. UAMS 2020. IM-Peds residency at UTHSC Memphis with training at St. Jude and Le Bonheur.",
    education: ["UAMS, Doctor of Medicine 2020", "UTHSC Memphis IM-Peds Residency"],
  },
  {
    name: "Dr. Sean Koch, MD",
    role: "Family Medicine",
    specialty: "Evidence-Based Primary Care",
    tags: ["wynne", "primary"],
    accepting: true,
    img: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=800&q=80&auto=format&fit=crop",
    bio: "Born in St. Louis, raised in Searcy. Harding University undergrad, UAMS medical school, three-year residency in Jonesboro.",
    education: ["UAMS, Doctor of Medicine", "Jonesboro Family Medicine Residency"],
  },
  {
    name: "Jill Davis",
    role: "Pediatric Nurse Practitioner",
    specialty: "MSN-RN, APRN, PNP-PC",
    tags: ["wynne", "pediatrics"],
    accepting: true,
    img: "https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=800&q=80&auto=format&fit=crop",
    bio: "Wynne native. Inaugural class of the accelerated BSN at Arkansas State. Former LeBonheur Trauma ER nurse and Wynne Public Schools district nurse before her MSN at UAMS in 2018.",
    education: ["UAMS, MSN 2018", "Arkansas State University, BSN 2008"],
  },
  {
    name: "Jodi Renigar",
    role: "Nurse Practitioner",
    specialty: "MSN-RN, FNP-BC, Women Health",
    tags: ["wynne", "primary", "urgent", "womens", "pediatrics"],
    accepting: true,
    img: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=800&q=80&auto=format&fit=crop",
    bio: "From Saint Francis County. Crowley Ridge LPN to EACC RN to Walden University MSN. Board certified in family practice with women health focus.",
    education: ["MSN, Walden University 2023"],
  },
  {
    name: "Whitney Reed",
    role: "Nurse Practitioner",
    specialty: "Family Practice, Board Certified",
    tags: ["lonoke", "primary", "urgent"],
    accepting: true,
    img: "https://images.unsplash.com/photo-1638202993928-7267aad84c31?w=800&q=80&auto=format&fit=crop",
    bio: "From Cabot. UAMS BSN 11, MSN 15. A decade of experience in primary and urgent care. Loves the Lonoke community.",
    education: ["UAMS, MSN 2015", "UAMS, BSN 2011"],
  },
  {
    name: "Erin OGuin",
    role: "Nurse Practitioner",
    specialty: "Family Practice, Patient-Centered Care",
    tags: ["wynne", "primary"],
    accepting: true,
    img: "https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=800&q=80&auto=format&fit=crop",
    bio: "Began at Arkansas State, master in nursing from Harding. Empowering patients across acute conditions, chronic illness, and prevention.",
    education: ["MSN, Harding University", "Arkansas State University"],
  },
];

export const INSURANCE = [
  { name: "BlueCross BlueShield Arkansas", accepted: true },
  { name: "Aetna", accepted: true },
  { name: "UnitedHealthcare", accepted: true },
  { name: "Cigna", accepted: true },
  { name: "Humana", accepted: true },
  { name: "Medicare", accepted: true },
  { name: "Medicaid (Arkansas)", accepted: true },
  { name: "ARKids First", accepted: true },
  { name: "TRICARE", accepted: true },
  { name: "QualChoice", accepted: true },
  { name: "Ambetter", accepted: true },
  { name: "HealthSCOPE Benefits", accepted: true },
  { name: "Self-pay (cash)", accepted: true, note: "Transparent self-pay pricing available." },
  { name: "Other plan", accepted: null, note: "Call your preferred clinic and we will verify your plan in minutes." },
];

export const RECOGNITIONS = [
  { name: "PCMH Level 3", explain: "Patient-Centered Medical Home, highest tier. Recognizes coordinated, accessible, evidence-based primary care." },
  { name: "Hypertension Champion", explain: "AMA / CDC recognition for outstanding control of high blood pressure across our patient panel." },
  { name: "Methodist Leadership Academy", explain: "Top 20 Memphis-region physicians invited to a year-long physician leadership program." },
  { name: "Crittenden County Medical Society", explain: "Active leadership in the local medical community, currently presiding." },
  { name: "Certified Wound Specialists", explain: "Hospital-trained CWS clinicians leading our advanced wound program." },
];

export const REVIEWS = [
  { quote: "Best clinic in the area. They actually listen.", author: "Kasey M.", date: "Mar 2026", source: "Google" },
  { quote: "Got us in same day for my son. Friendly and fast.", author: "Ryan P.", date: "Feb 2026", source: "Google" },
  { quote: "Front desk is incredible. Felt taken care of.", author: "Grace W.", date: "Feb 2026", source: "Google" },
  { quote: "Wound healed quickly with their advanced care team.", author: "James T.", date: "Jan 2026", source: "Google" },
  { quote: "My pediatrician of choice. Calm and gentle visits.", author: "Maria L.", date: "Jan 2026", source: "Google" },
  { quote: "Best healthcare experience I have had in years.", author: "Daniel K.", date: "Dec 2025", source: "Google" },
];

export const TESTIMONIALS = [
  {
    quote: "It was my first visit to Harmony Health Clinic and overall it was a great experience. The staff was so friendly and extremely knowledgeable. I felt very comfortable and am so thankful my friend referred them to me.",
    author: "Kasey M.",
    location: "Wynne",
    date: "March 2026",
  },
  {
    quote: "The team at Harmony Health Clinic are experienced and caring individuals. They are focused on helping their patients and have treatments to fit your needs. I would recommend them to my friends and family.",
    author: "Grace W.",
    location: "Lonoke",
    date: "February 2026",
  },
  {
    quote: "I had an amazing experience taking my son to Harmony Health Clinic. He has always been afraid of the doctor office, but the team was so patient and really made him feel comfortable. It was such a pleasant trip.",
    author: "Ryan P.",
    location: "Wynne",
    date: "January 2026",
  },
];

export const FAQ = [
  {
    q: "Are you accepting new patients?",
    a: "Yes. Most providers across all four locations are accepting new patients. Filter the team grid by your preferred location to see who is currently available.",
    cta: { label: "See providers accepting patients", target: "team" },
  },
  {
    q: "What insurance do you accept?",
    a: "Harmony Health accepts most major insurance plans including BlueCross BlueShield, Aetna, UHC, Cigna, Humana, Medicare, Medicaid, and ARKids First. Use the insurance checker above to verify your plan.",
    cta: { label: "Verify your insurance plan", target: "insurance" },
  },
  {
    q: "Do you offer same-day appointments?",
    a: "Yes. Same-day urgent care visits are available at Wynne and most other locations during business hours. Call ahead so we can prepare your visit and give you an accurate wait time.",
    cta: { label: "Reserve an urgent care slot", target: "book" },
  },
  {
    q: "What is the difference between urgent care and the ER?",
    a: "Urgent care handles non-life-threatening illness and minor injuries quickly and at lower cost than the ER. For chest pain, stroke symptoms, severe bleeding, or trauma, call 911 or go to the nearest ER.",
    cta: { label: "See full urgent vs ER guide", target: "urgent-er" },
  },
  {
    q: "Can I get my labs done in-office?",
    a: "Yes. Harmony Health Clinic offers in-house diagnostics and lab services to streamline your visit and reduce time to results.",
    cta: { label: "Explore our services", target: "services" },
  },
  {
    q: "How do I access my records?",
    a: "Use the MyChart Patient Portal to view records, request refills, and message your care team.",
    cta: { label: "Open MyChart Patient Portal", external: "https://epicconnect.org/ccprd/CommunityConnect/mychartcc.html" },
  },
];

export const RESOURCES = [
  {
    title: "Flu season prep, what actually works",
    excerpt: "A short evidence-based guide to vaccines, when to visit, and what to do at home for adults and kids.",
    tag: "Prevention",
    minutes: 5,
    img: "/assets/clinic-room.jpg",
  },
  {
    title: "Childhood immunization schedule, simplified",
    excerpt: "What your child needs and when, from birth through teens, with answers to the most common parent questions.",
    tag: "Pediatrics",
    minutes: 7,
    img: "/assets/about.jpg",
  },
  {
    title: "Living well with diabetes, day to day",
    excerpt: "Practical habits that move your A1C, plus what to ask your provider at every visit.",
    tag: "Chronic care",
    minutes: 6,
    img: "/assets/services.jpg",
  },
];
